# Generated by Django 4.2.5 on 2023-09-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
